language: node_js
node_js:
  - "15.5.0"

branches:
  only:
  - master
  - dev

before_install:
  - npm install -g @ionic/cli @angular/cli

install:
  - npm ci

jobs:
  include:
  - stage: test
    before_script: cd OpenOralBibleClient
    script: npm run ci-test