language: android
sudo: false
node_js:
  - "15.5.0"

branches:
  only:
  - master
  - dev

before_install:
  - sudo apt-get install npm
  - npm i -g npm@7.3.0
  - npm install -g @ionic/cli @angular/cli cordova

install:
  - cd OpenOralBibleClient
  - npm ci

jobs:
  include:
  - stage: test
    script: npm run ci-test
  - stage: package
    script: npm run package