language: node_js
sudo: false
node_js:
  - "15.5.0"

addons:
  apt:
    packages:
      - oracle-java8-set-default

branches:
  only:
  - master
  - dev

before_install:
  - sudo apt-get install android-sdk
  - npm install -g @ionic/cli @angular/cli cordova

install:
  - cd OpenOralBibleClient
  - npm ci

jobs:
  include:
  - stage: test
    script: npm run ci-test
  - stage: package
    script: npm run package