language: android
sudo: false

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

addons:
  apt:
    sources:
      - sourceline: deb http://dl.google.com/linux/chrome/deb/ stable main
        key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    packages:
      - google-chrome-stable

licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

branches:
  only:
  - master
  - dev

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - nvm install 15
  - npm install -g @ionic/cli @angular/cli cordova
  - export CHROME_BIN=google-chrome
  - google-chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - cd OpenOralBibleClient
  - npm ci

jobs:
  include:
  - stage: test
    script: npm run ci-test
  - stage: package
    script: npm run package

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - CHROME_BIN=google-chrome