language: node_js

branches:
  only:
  - master
  - dev

before_script:
 — npm install -g ionic
 — npm ci

jobs:
  include:
  - stage: test
    before_script: cd OpenOralBibleClient
    script: npm test