language: android
sudo: false

addons:
  chrome: stable

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository

branches:
  only:
  - master
  - dev

before_install:
  - apt install google-chrome-stable
  - nvm install 15
  - npm install -g @ionic/cli @angular/cli cordova
  - export CHROME_BIN=google-chrome-stable
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - cd OpenOralBibleClient
  - npm ci

jobs:
  include:
  - stage: test
    script: npm run ci-test
  - stage: package
    script: npm run package

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - CHROME_BIN=google-chrome-stable