language: node_js

branches:
  only:
  - master
  - dev

before_install:
  — npm install -g ionic @angular/cli
  — npm ci

jobs:
  include:
  - stage: test
    before_script: cd OpenOralBibleClient
    script: npm run ci-test